2024-10-31 17:14:27,605 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:14:27,606 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:14:27,640 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:14:27,672 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:14:27,715 - INFO - Authentication (publickey) failed.
2024-10-31 17:14:27,725 - INFO - Authentication (password) successful!
2024-10-31 17:14:27,768 - INFO - Authentication (publickey) failed.
2024-10-31 17:14:27,787 - INFO - Authentication (password) successful!
2024-10-31 17:14:27,954 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:14:39,216 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:23:09,746 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:23:09,746 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:23:09,782 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:23:09,783 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:23:09,850 - INFO - Authentication (publickey) failed.
2024-10-31 17:23:09,853 - INFO - Authentication (publickey) failed.
2024-10-31 17:23:09,860 - INFO - Authentication (password) successful!
2024-10-31 17:23:09,863 - INFO - Authentication (password) successful!
2024-10-31 17:23:09,985 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:23:18,015 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:25:00,715 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:25:00,715 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:25:00,748 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:25:00,749 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:25:00,820 - INFO - Authentication (publickey) failed.
2024-10-31 17:25:00,821 - INFO - Authentication (publickey) failed.
2024-10-31 17:25:00,830 - INFO - Authentication (password) successful!
2024-10-31 17:25:00,831 - INFO - Authentication (password) successful!
2024-10-31 17:25:00,960 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:25:08,997 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:25:49,547 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:25:49,547 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:25:49,580 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:25:49,581 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:25:49,648 - INFO - Authentication (publickey) failed.
2024-10-31 17:25:49,652 - INFO - Authentication (publickey) failed.
2024-10-31 17:25:49,658 - INFO - Authentication (password) successful!
2024-10-31 17:25:49,662 - INFO - Authentication (password) successful!
2024-10-31 17:25:49,769 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py broker_ip 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:25:58,021 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py broker_ip 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:26:10,053 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:26:10,053 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:26:10,085 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:26:10,087 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:26:10,154 - INFO - Authentication (publickey) failed.
2024-10-31 17:26:10,155 - INFO - Authentication (publickey) failed.
2024-10-31 17:26:10,165 - INFO - Authentication (password) successful!
2024-10-31 17:26:10,165 - INFO - Authentication (password) successful!
2024-10-31 17:26:10,288 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:26:18,379 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/dev/dtrack && python mqtt_subscriber.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:28:21,368 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:28:21,368 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:28:21,446 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:28:21,447 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:28:21,518 - INFO - Authentication (publickey) failed.
2024-10-31 17:28:21,529 - INFO - Authentication (password) successful!
2024-10-31 17:28:21,541 - INFO - Authentication (publickey) failed.
2024-10-31 17:28:21,552 - INFO - Authentication (password) successful!
2024-10-31 17:28:21,704 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && python mqtt_subscriber.py A 10.0.0.14'

Exit code: 2

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:28:21,723 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && python mqtt_subscriber.py A 10.0.0.14'

Exit code: 2

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:28:37,395 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:28:37,395 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:28:37,428 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:28:37,429 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:28:37,496 - INFO - Authentication (publickey) failed.
2024-10-31 17:28:37,507 - INFO - Authentication (password) successful!
2024-10-31 17:28:37,541 - INFO - Authentication (publickey) failed.
2024-10-31 17:28:37,552 - INFO - Authentication (password) successful!
2024-10-31 17:28:37,674 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:28:37,734 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:32:58,015 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:32:58,015 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:32:58,050 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:32:58,052 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:32:58,161 - INFO - Authentication (publickey) failed.
2024-10-31 17:32:58,164 - INFO - Authentication (publickey) failed.
2024-10-31 17:32:58,171 - INFO - Authentication (publickey) failed.
2024-10-31 17:32:58,174 - INFO - Authentication (publickey) failed.
2024-10-31 17:32:58,181 - INFO - Authentication (password) successful!
2024-10-31 17:32:58,184 - INFO - Authentication (password) successful!
2024-10-31 17:32:58,364 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:33:01,821 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:37:06,242 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:37:06,242 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:37:06,275 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:37:06,276 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:37:06,345 - INFO - Authentication (publickey) failed.
2024-10-31 17:37:06,346 - INFO - Authentication (publickey) failed.
2024-10-31 17:37:06,357 - INFO - Authentication (publickey) failed.
2024-10-31 17:37:06,357 - INFO - Authentication (publickey) failed.
2024-10-31 17:37:06,366 - INFO - Authentication (password) successful!
2024-10-31 17:37:06,367 - INFO - Authentication (password) successful!
2024-10-31 17:37:24,280 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:37:26,075 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:39:31,330 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:39:31,330 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:39:31,362 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:39:31,363 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:39:31,436 - INFO - Authentication (publickey) failed.
2024-10-31 17:39:31,437 - INFO - Authentication (publickey) failed.
2024-10-31 17:39:31,447 - INFO - Authentication (publickey) failed.
2024-10-31 17:39:31,447 - INFO - Authentication (publickey) failed.
2024-10-31 17:39:31,458 - INFO - Authentication (password) successful!
2024-10-31 17:39:31,459 - INFO - Authentication (password) successful!
2024-10-31 17:39:44,046 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:39:44,329 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:41:02,847 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:41:02,848 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:41:02,880 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:41:02,913 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:41:02,950 - INFO - Authentication (publickey) failed.
2024-10-31 17:41:02,961 - INFO - Authentication (publickey) failed.
2024-10-31 17:41:02,972 - INFO - Authentication (password) successful!
2024-10-31 17:41:03,004 - INFO - Authentication (publickey) failed.
2024-10-31 17:41:03,015 - INFO - Authentication (publickey) failed.
2024-10-31 17:41:03,033 - INFO - Authentication (password) successful!
2024-10-31 17:41:21,569 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:41:23,651 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py A 10.0.0.14'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:43:09,226 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:43:09,226 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:43:09,259 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:43:09,298 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:43:09,328 - INFO - Authentication (publickey) failed.
2024-10-31 17:43:09,339 - INFO - Authentication (publickey) failed.
2024-10-31 17:43:09,349 - INFO - Authentication (password) successful!
2024-10-31 17:43:09,369 - INFO - Authentication (publickey) failed.
2024-10-31 17:43:09,379 - INFO - Authentication (publickey) failed.
2024-10-31 17:43:09,389 - INFO - Authentication (password) successful!
2024-10-31 17:43:27,848 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py 10.0.0.14'

Exit code: 2

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:43:28,075 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py 10.0.0.14'

Exit code: 2

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:43:52,690 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:43:52,694 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:43:52,721 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:43:52,725 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:43:52,792 - INFO - Authentication (publickey) failed.
2024-10-31 17:43:52,793 - INFO - Authentication (publickey) failed.
2024-10-31 17:43:52,802 - INFO - Authentication (publickey) failed.
2024-10-31 17:43:52,803 - INFO - Authentication (publickey) failed.
2024-10-31 17:43:52,814 - INFO - Authentication (password) successful!
2024-10-31 17:43:52,815 - INFO - Authentication (password) successful!
2024-10-31 17:44:16,173 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py 10.0.0.14 1883'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:44:16,184 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py 10.0.0.14 1883'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:45:31,712 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 17:45:31,712 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 17:45:31,745 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:45:31,746 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 17:45:31,814 - INFO - Authentication (publickey) failed.
2024-10-31 17:45:31,815 - INFO - Authentication (publickey) failed.
2024-10-31 17:45:31,824 - INFO - Authentication (publickey) failed.
2024-10-31 17:45:31,825 - INFO - Authentication (publickey) failed.
2024-10-31 17:45:31,834 - INFO - Authentication (password) successful!
2024-10-31 17:45:31,835 - INFO - Authentication (password) successful!
2024-10-31 17:45:54,923 - ERROR - Error starting subscriber on 10.0.0.17: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py 10.0.0.14 1883'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 17:45:55,086 - ERROR - Error starting subscriber on 10.0.0.15: Encountered a bad command exit code!

Command: 'cd /home/dtrack/D-Track-Alpha/calibration_suite/ && sudo ./setup_node_for_calibration.sh && source camera-node/bin/activate && python slave_calibrator.py 10.0.0.14 1883'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)


2024-10-31 19:24:27,344 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 19:24:27,345 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 19:24:27,383 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 19:24:27,383 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 19:24:27,456 - INFO - Authentication (publickey) failed.
2024-10-31 19:24:27,457 - INFO - Authentication (publickey) failed.
2024-10-31 19:24:27,467 - INFO - Authentication (publickey) failed.
2024-10-31 19:24:27,467 - INFO - Authentication (publickey) failed.
2024-10-31 19:24:27,476 - INFO - Authentication (password) successful!
2024-10-31 19:24:27,477 - INFO - Authentication (password) successful!
2024-10-31 19:49:11,859 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 19:49:11,861 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 19:49:11,940 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 19:49:11,940 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 19:49:12,025 - INFO - Authentication (publickey) failed.
2024-10-31 19:49:12,025 - INFO - Authentication (publickey) failed.
2024-10-31 19:49:12,042 - INFO - Authentication (publickey) failed.
2024-10-31 19:49:12,043 - INFO - Authentication (publickey) failed.
2024-10-31 19:49:12,057 - INFO - Authentication (password) successful!
2024-10-31 19:49:12,060 - INFO - Authentication (password) successful!
2024-10-31 19:50:27,870 - INFO - Starting subscriber on 10.0.0.15
2024-10-31 19:50:27,876 - INFO - Starting subscriber on 10.0.0.17
2024-10-31 19:50:27,951 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 19:50:27,952 - INFO - Connected (version 2.0, client OpenSSH_9.2p1)
2024-10-31 19:50:28,033 - INFO - Authentication (publickey) failed.
2024-10-31 19:50:28,037 - INFO - Authentication (publickey) failed.
2024-10-31 19:50:28,046 - INFO - Authentication (publickey) failed.
2024-10-31 19:50:28,050 - INFO - Authentication (publickey) failed.
2024-10-31 19:50:28,059 - INFO - Authentication (password) successful!
2024-10-31 19:50:28,062 - INFO - Authentication (password) successful!
